### ISSUE TITLE
TODO Release 1.0-rc1

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/memgator#22]
# Release Checklist

* [x] Review the milestone and move issues in other milestones, if necessary
* [x] Close all the remaining milestone issues except this one
* [x] Bump the version number
* [x] Compile the binaries for various platforms
* [x] Release binaries with descriptive release note
* [x] Close this issue and this milestone

**Comment by ibnesayeed** [comment]
[1.0-rc1 is released](https://github.com/oduwsdl/memgator/releases/tag/1.0-rc1).
