### ISSUE TITLE
TODO Release 1.1

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/memgator#24]
# Release Checklist

* [ ] Review the milestone and move issues in other milestones, if necessary
* [ ] Close all the remaining milestone issues except this one
* [ ] Bump the version number
* [ ] Compile the binaries for various platforms
* [ ] Release binaries with descriptive release note
* [ ] Announce the release on social media such as Twitter
* [ ] Close this issue and this milestone
